server:
  port: 9003
spring:
  application:
    name: dolphin-pay-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?useSSL=false
    username: root
    password: P@ssw0rd
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  redis:
    host: ${redis}
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos}
  profiles:
    active: ${gok-env}

mybatis-plus:
  mapper-locations: classpath:mapper/*/*-mapper.xml
  type-aliases-package: cn.goktech.dolphin.pay.entity
  configuration:
    log-prefix: dao.
    map-underscore-to-camel-case: true

ignore:
  urls:
    - /actuator/**
    - /pay/**

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true


# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000

# 防止第一次调用超时，使用eagerLoad模式
#ribbon:
#  eager-load:
#    enabled: true
#    clients: dolphin-upms-service

seq:
  zkAddr: 192.168.2.218:2181
  distribute: false


