server:
  port: 7400

spring:
  application:
    name: dolphin-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: dolphin-upms-service
          uri: lb://dolphin-upms-service
          predicates:
            - Path=/uaa/sys/**
          filters:
            - StripPrefix=1
        - id: dolphin-auth-service
          uri: lb://dolphin-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: ${nacos}

feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000